# Form implementation generated from reading ui file '/home/jithin/Github/MuseScore/src/palette/view/widgets/keyedit.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KeyEdit(object):
    def setupUi(self, KeyEdit):
        KeyEdit.setObjectName("KeyEdit")
        KeyEdit.resize(636, 360)
        KeyEdit.setWindowTitle("")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(KeyEdit)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.splitter = QtWidgets.QSplitter(KeyEdit)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.keySigframe = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keySigframe.sizePolicy().hasHeightForWidth())
        self.keySigframe.setSizePolicy(sizePolicy)
        self.keySigframe.setObjectName("keySigframe")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
